import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import Error from "./error";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import NavbarWrapper from "@/components/header/NavbarWrapper";
import { Providers } from "@/lib/Providers";
import Script from 'next/script'
import { Analytics } from './analytic'

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
});

const suwannaphum = localFont({
  src: [
    {
      path: '../../public/fonts/Suwannaphum-Black.ttf',
      weight: '900',
      style: 'black',
    },
    {
      path: '../../public/fonts/Suwannaphum-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/fonts/Suwannaphum-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Suwannaphum-Light.ttf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../../public/fonts/Suwannaphum-Thin.ttf',
      weight: '100',
      style: 'thin',
    }
  ],
  variable: "--font-suwannaphum",
  display: "swap",
})


export const metadata: Metadata = {
  title: "ENV ft Tanstack",
  description: "Generated by create next app",
  openGraph:{
    title: "Testing ENV With Tanstack",
    description: "Ot jg dak te, lazy to sse",
    siteName: "Next.js App",
    images: "https://media.istockphoto.com/id/482834907/photo/binary.jpg?s=612x612&w=0&k=20&c=wfMtMTBUkV_N269G-Vqs_EcWzovva8p9ebcW2o_VPPE=",
    locale: "en_US",
    type: "website",

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Script */}
          <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
          />
          <Script id=
          "google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
          `}
          </Script>
      </head>
      <body
        className={`${ubuntu.variable} ${suwannaphum.variable} antialiased`}
      >
        <Providers>
                  <ErrorBoundary errorComponent={Error}>
          
          <Suspense fallback={<Loading />}>
          <NavbarWrapper />
          <Analytics />
            {children}
          </Suspense>
        </ErrorBoundary>
        </Providers>

      </body>
    </html>
  );
}
